from moment import moment


EPOCH_DEFAULT = 1608480000
EPOCH_MOMENT = moment('2020-12-21')

ACTION_ID_BITS = 12
ACTION_STATE_BITS = 2
RANDOM_CODE_BITS = 6
NIC_BITS = 24
POSITION_CODE_BITS = 4
TIMESTAMP_BITS = 42
TIMESTAMP_SHADOW_BITS = 48
EVENT_ID_BITS = 96

POSITION_CODE_MIN = 0
POSITION_CODE_MAX = 7

RANDOM_CODE_MIN = 0
RANDOM_CODE_MAX = (1 << RANDOM_CODE_BITS) - 1

ACTION_ID_MIN = 0
ACTION_ID_MAX = (1 << ACTION_ID_BITS) - 1

STATE_MIN = 0
STATE_MAX = (1 << ACTION_STATE_BITS) - 1
STATE_INIT = STATE_MIN
STATE_END = STATE_MAX

KEY_MAX = 'max'
KEY_MIN = 'min'
KEY_LEN = 'len'

BIN_REG = '{0:0{1}b}'
HEX_REG = '{0:0{1}x}'

EVENT_ID_LEN = 24
TS_PACKAGE_LEN = 8
